### ISSUE TITLE
HTML tables get modified by `distill`

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/distill#159]
Cross-posting this from `gt` Issue #643 [here](https://github.com/rstudio/gt/issues/643).

---
The `distill` RMarkdown format appears to override portions of `gt` tables. This leads to double "plotting" of header borders, and adds row dividers even if they've been excluded via `tab_options()`.

This also appears to occur with [`kableExtra`](https://github.com/haozhu233/kableExtra/issues/279) and further documented [here](https://haozhu233.github.io/kableExtra/using_kableExtra_in_radix.html).

My assumption is that there is a `boostrap` or `CSS` conflict. If it's more appropriate to reference this in the `distill` repo let me know!

```r
library(gt)

mtcars %>% 
  head() %>% 
  gt() %>% 
  tab_spanner(
    2:5,
    label = "Spanner"
  ) %>% 
  tab_options(
    table_body.hlines.color = "white",
    column_labels.border.bottom.width = px(3),
    column_labels.border.bottom.color = "black",
    table.border.top.color = "white",
    table.border.top.width = px(3),
    table.border.bottom.color = "black",
    table.border.bottom.width = px(3)
  )
```

### V1 - as seen from console

![Screen Shot 2020-09-09 at 4 55 42 PM](https://user-images.githubusercontent.com/29187501/92659101-5bbbda80-f2bd-11ea-84f4-6cd3888c6e20.png)

### V2 - as seen in `distill`

Notice the gray lines behind the spanner and for h-lines.

![Screen Shot 2020-09-09 at 4 55 30 PM](https://user-images.githubusercontent.com/29187501/92659103-5ced0780-f2bd-11ea-9971-8abac1799dbe.png)

**Comment by jjallaire** [comment]
I think we just need to turn off distill's table CSS when we detect kableExtra, gt, etc. Should be pretty straightforward.

**Comment by jjallaire** [comment]
These particular issues should be addressed with this commit: https://github.com/rstudio/distill/commit/f7bab91278f4c8b1c3fdbb288f334421ab112ff7

@rich-iannone Here are all of the default styles defined by distill for tables: https://github.com/distillpub/template/blob/7e240ddf4f15748b74aa162ce0c00c60699e9027/src/styles/d-article.css#L234-L262

Do you expect that we'd have additional troubles/conflicts we should proactively work around based on what you see here?

In terms of kableExtra, it looks to me like the underlying issue is that it assumes that bootstrap.css will be available. They've got a workaround now for distill (and other formats) to auto-include that CSS so we shouldn't need to do anything more (but do LMK if there is indeed something we could do to make that work better).

**Comment by jthomasmock** [comment]
I can confirm that as far as I can tell this fixes the issues I reported above!

**Comment by jjallaire** [comment]
Okay, I'll close this one then. If there are other table display problems let's open up new issues for them.
