### ISSUE TITLE
Support for code folding

### ISSUE THREAD

**Issue by jthomasmock** [rstudio/distill#160]
Currently, `distill` doesn't support native cold-folding as implemented by `RMarkdown` YAML:

Thus, the below doesn't work.

````
---
output:
  html_document:
    code_folding: show
---
```{r}
1
```
```{r, class.source='fold-hide'}
2
```
````

# Alternatives

### `codefolder` via JS

Ian Lyttle has created a small R package to enable code folding [here](https://github.com/ijlyttle/codefolder)  
  - Based off this [StackOverflow post](https://stackoverflow.com/a/45501553)

### `<details>` via CSS

You can use a [`<details><summary> NAME </summary> HIDDEN TEXT OR CODE CHUNK </details>`](https://github.com/mrworthington/mrworthington.github.io/blob/master/styles.css#L106-L154) HTML fragment to create folding portions which was also integrated into `RMarkdown` by `knitr` hooks as seen [here](https://github.com/rstudio/rmarkdown/issues/664). However, expandable `<details>` sections appear to break gutter text and `<aside>`.

**Comment by mrworthington** [comment]
I'm happy to share how I did the modified the <details> chunk for code folding [here](https://www.mrworthington.com/posts/covid_atx/). It's less elegant and more hack-y for sure, but I basically just adopted some code from the distill.pub site. I also have another site I'm developing for work that I can't share publicly, but am using distill and doing a lot of custom stuff like making landing pages. page-headers with image overlay backgrounds and table of contents on the side. Would love to share it with y'all if you're interested.

**Comment by jjallaire** [comment]
Code folding has been implemented, docs here: https://rstudio.github.io/distill/#code-folding

**Comment by njudd** [comment]
There was odd behavior on this feature in distill (or maybe it's standard and I just struggled with it)... Regardless I am going to put it here so future people and see it.

If you want some sections to fold and others to not (yet **also not echo**, you need to leave the code folding argument empty). If you choose code_folding: True (or any text which is also true), then when you tell a chunk not to fold it will echo. Even if you have knitr::opts_chunk$set(echo = FALSE). If you choose false, you can't call code_folding on the chunk.

```
---
title: "Localized and global causes"
author:
output:
  distill::distill_article:
    code_folding: 
---
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r norm one, code_folding = T}
ct1 <- rnorm(1000)
```
Expected behavior folds.

```{r norm two, code_folding = F}
ct2 <- rnorm(10000)
```
Echo's (this also happens if you add the chunk option echo = F)

```{r print two}
length(ct2)
```
Works nicely when you leave the code_folding argument empty!

**Comment by cderv** [comment]
🤔 this sound like a bug somewhere. I'll put your comment in a new issue so that I don't forget to check.
