### ISSUE TITLE
Is there an easy way to change the theme?

### ISSUE THREAD

**Issue by znmeb** [rstudio/distill#19]
From what I've been able to glean from the documentation, the only way to change the theme on a Radix site is with raw CSS code. That's a non-starter for a lot of people; is there another way to do it?

**Comment by jjallaire** [comment]
No there isn't a way to change the theme. Part of the idea of Radix is to enforce a uniform theme so that it's easy to aggregate lots of articles written in different places together (e.g. for a blog or journal).  This is philosophically a bit like the https://medium.com blogging service.

**Comment by JulianSpagnuolo** [comment]
So those that don't want to deal with css are stuck with the default rendering of very tiny text?

**Comment by JulianSpagnuolo** [comment]
The text size in the TOC is way too small (also in the citation part). I had also seen the text in the body render as small as the TOC (even on a 20" screen).

I also would like to see numbered headers as supported in the standard knitr and rmarkdown html formats.

<img width="936" alt="screen shot 2018-10-05 at 10 01 22" src="https://user-images.githubusercontent.com/26929468/46523389-dd12c300-c885-11e8-912d-506cb724c3f3.png">

**Comment by jjallaire** [comment]
I think everyone has different opinions about appropriate font sizes. One reason that smaller sizes are used is to make the text diminutive relative to the body. It's certainly all a bit subjective. Radix is an opinionated format (based on Distill, which has very strong opinions as well) and the choices made won't sit well for everyone all the time.

Since there are literally dozens of style elements to tweak providing YAML options for each of them is not realistic. The best way to handle this is CSS (which can pretty much allow you to do *anything* you want with the styling and then re-use the changes across documents). For example, you can add this inline `css` chunk to your Rmd to change the fonts in the table of contents:

    ```{css}
    .d-toc-header {
      font-size: 0.9rem;
    }

    .d-toc {
      font-size: 1.0rem
    }
    ``` 

In terms of numbered sections, the problem here is that pandoc wants to number sections using level 1 headers and Distill/Radix documents styles are based on using level 2 headers for major document sections. I've played with trying to resolve this tension and it's frustratingly difficult to overcome.

**Comment by apreshill** [comment]
@JulianSpagnuolo @znmeb we now have a theming system for distill and docs are here ✨ 

https://rstudio.github.io/distill/website.html#theming
