### ISSUE TITLE
Numbering of figures no longer working

### ISSUE THREAD

**Issue by wordsmith189** [rstudio/distill#202]
Good morning,

Ever since I updated to the working version of distill yesterday, the automatic numbering of figures isn't working anymore for me.  

I just downloaded and installed the newest versions of R, RStudio, knitr, and the github version of distill. 

Here is [a post that shows the output I'm getting](https://titus-and-shrew.netlify.app/posts/some-numbers/).

Thank you for any pointers!

**Comment by jjallaire** [comment]
This is working as expected for me when running the dev/master versions of distill and rmarkdown, and with the other package versions listed in the output here:

https://rpubs.com/jjallaire/test-distill-figures

Here's my source-code for this output:

````markdown
---
title: "test figures"
output: distill::distill_article
---

```{r fig.cap="cars plot"}
plot(cars)
```

```{r fig.cap="pressure plot"}
plot(pressure)
```

```{r}
options(width = 80)
devtools::session_info()
```
````

Could you verify that your package versions are similar (esp. your version of bookdown) and try again?

**Comment by cderv** [comment]
Hi @wordsmith189, 

I think this is because you have some spaces in your chunk label
https://github.com/wordsmith189/analyzing-shrew/blob/94e92b0a3c2cadf55c99944a777d20f9ab406386/_posts/some-numbers/some-numbers.Rmd#L61

If I add some in @jjallaire  example, I can reproduce 
````md
---
title: "test figures"
output: distill::distill_article
---

```{r n words char, fig.cap="cars plot"}
plot(cars)
```
````

Spaces in labels names are not supported, specifically for the figure numbering mechanism - you should put `-` instead. 

I wonder if we could warn about that 🤔

**Comment by wordsmith189** [comment]
Yes - that was the reason.
Initially I replaced spaces in the chunk names for _ and that did not work
either. But then I just deleted them and it's working now. I suspect that
the minus (rather than underscore) would also work, right?

Thanks!

>

**Comment by cderv** [comment]
Yes the minus would work. Underscore does not work for figure referencing.
