### ISSUE TITLE
Upgrade a11y highlighter

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#209]
+ `#f7f7f8` (.at) flagged as low contrast

+ `#D91E18` "cn" is a bit too bright too- maybe switch to `#A1024A`. In downlit:
    ```
    constant <- c(
        "NA", "Inf", "NaN", "TRUE", "FALSE",
        "NA_integer_", "NA_real_", "NA_character_", "NA_complex_"
     )
    ```

+ consider pulling the colours "40%" towards a fixed chroma

+ remove bolds

Code from @hadley for calculating contrast ratios:
```
rel_l <- function(x) {
  scale <- function(x) {
    ifelse(x <= 0.03928, x / 12.92, ((x + 0.055) / 1.055)^2.4)
  }
  rgb <- farver::decode_colour(x) / 255
  0.2126 * scale(rgb[, 1]) + 0.7152 * scale(rgb[, 2]) + 0.0722 * scale(rgb[, 3])
}
contrast_ratio <- function(x, y) {
  x_l <- rel_l(x)
  y_l <- rel_l(y)
  (pmax(x_l, y_l) + 0.05) / (pmin(x_l, y_l) + 0.05)
}
```

Also gist from @hadley for parsing the theme into CSS:
https://gist.github.com/hadley/f53b6e92df20994fdabe6562d284728a

**Comment by mondpanther** [comment]
I am having a problem with distill after upgrading that might have to do with this feature.
Here is the error message:

Unknown highlight-style C:\Users\RALFMA~1\DOCUME~1\R\WIN-LI~1\4.0\distill\RMARKD~1\TEMPLA~1\DISTIL~1\RESOUR~1\A11Y~1.THE
Error: pandoc document conversion failed with error 2
In addition: Warning message:
In (function (category = "LC_ALL", locale = "")  :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
Execution halted


Can you help? Because of this I am not able to compile any distill documents anymore. I tried to re-install everything (r and rstudio, also wiped any traces of pandoc) but the error remains.

**Comment by jjallaire** [comment]
What version of pandoc are you using? It's possible that you are using a version which doesn't support highlight themes?

You can determine the version as follows `rmarkdown::pandoc_version()`

**Comment by mondpanther** [comment]
The one that comes with Rstudio..However, while trying to solve the problem I also installed the latest pandoc version separately.

Having said all that: I now reverted back to distill 0.8 and everything works....so I really think it has to do with your new version 1.0

**Comment by mondpanther** [comment]
rmarkdown::pandoc_version()
[1] ‘2.7.3’

**Comment by apreshill** [comment]
@mondpanther would you mind opening a new issue to track? I created this issue and will be closing today with a PR, so I want to make sure we track it elsewhere. Thanks!

**Comment by jjallaire** [comment]
I see that pandoc has supported theme files since 2.0.4 so it's not the pandoc version. It may be an issue with paths on windows? I see that we are correctly calling `rmarkdown::pandoc_path_arg()` for the highlighting style so on the surface it doesn't seem like this would be the cause of failure.

**Comment by mondpanther** [comment]
> 
> 
> @mondpanther would you mind opening a new issue to track? I created this issue and will be closing today with a PR, so I want to make sure we track it elsewhere. Thanks!

will do

**Comment by cderv** [comment]
For reference done in https://github.com/rstudio/distill/issues/214
