### ISSUE TITLE
Error when knitting posts in the _posts directory

### ISSUE THREAD

**Issue by jmbuhr** [rstudio/distill#224]
After updating to the latest commit, I get an error message when I try to knit a post. This happens with the example post created by `create_post` as well:

```
Error in read_xml.character(file) : 
  Specification mandates value for attribute disabled [41]
Calls: <Anonymous> ... fixup_navigation_paths -> <Anonymous> -> read_xml.character
Execution halted
```

**Comment by jmbuhr** [comment]
I belive this is where the error occurs: https://github.com/rstudio/distill/blob/c8591adabb550d1417bbd3933ae057eef57d4914/R/navigation.R#L279

Does this need to be `read_html` instead of `xml`?

**Comment by cderv** [comment]
Hi @jmbuhr , 

what example did you follow ? I can't reproduce following example in https://rstudio.github.io/distill/blog.html#creating-a-post

If you have more information so that we can try to recreate your issue, this would be great. With a template distill blog, and following the example, I can knit a post.

Can you share also your session info : `sessioninfo::session_info("distill")`

Thank you

**Comment by jmbuhr** [comment]
I am sorry, it was just me. Apparently the parser doesn't like me loading a stylesheet with the property "disabled" in the `_footer.html` to create a hacky switchable darkmode
