### ISSUE TITLE
horizontal scrolling when code too wide

### ISSUE THREAD

**Issue by feddelegrand7** [rstudio/distill#258]
Hi, 

when the code output is too wide, the horizontal scroll is disable (see image below). I've fixed the problem using the following CSS code, hope it's helpful: 

d-article pre, d-article div.sourceCode, d-article div.sourceCode pre {
    overflow: auto !important;
}

 

![image](https://user-images.githubusercontent.com/28841210/103036140-4ff0dd00-4569-11eb-85c4-6039e477c205.png)

**Comment by jjallaire** [comment]
This is a difficult concern to resolve well for all cases. The reason that it's currently "visible" is so that you can spill code into the right margin (as it doesn't always fit neatly into the center column). If we set it to "auto" then it actually gets clipped into the center column, which would cause many cases where code is currently displayed overlapping the right margin to appear clipped (via the scroll treatment).

**Comment by feddelegrand7** [comment]
Hi, 

I don't understand exactly the issue as I don't have this broader vue of the package's styling and I'm not that fluent in CSS but for me it's working like a charm (see below). Anyway, thank you very much for the package, I'm enjoying it :) 

Best.
![image](https://user-images.githubusercontent.com/28841210/103238025-bb5ff380-4949-11eb-944d-9d02d91d9f44.png)

**Comment by jjallaire** [comment]
It definitely works as you've done it, what I am trying to say is that frequently users want the code to overflow into the right margin (rather than getting clipped into the main body). This generally "works" because it's relatively easy to format code to fit within 80 columns (although your motivating example clearly isn't one of those cases).

**Comment by feddelegrand7** [comment]
Ah yes ! you're absolutely right, I think this problem arises mainly when using long URLs.
