### ISSUE TITLE
search appears only in mobile version?

### ISSUE THREAD

**Issue by werkstattcodes** [rstudio/distill#264]
I installed distill from github.

When creating a new blog from RStudio's new project menu and subsequently build the site, the search field is only visible in 'mobile view', but not in the browser e.g. on my laptop. I did not change any of the settings following the creation of the project.

Is this a bug in the dev version, or am I missing something? Many thanks!

**Comment by jjallaire** [comment]
I believe that this is because in the browser it's being served off of the filesystem (and the search library we use can't load the index from the filesystem). When you deploy it or if you run it with a local webserver (e.g https://github.com/yihui/servr) then you should see the search field.

Will close this, feel free to re-open if you find it doesn't work even when run with a web server.
