### ISSUE TITLE
chunk options code_folding=F and echo=F nevertheless shows code

### ISSUE THREAD

**Issue by werkstattcodes** [rstudio/distill#297]
When setting the chunk options to 'show output only' (`echo=F`) and specify `code_folding=F` I get  e.g. the plot (as desired) plus the code which produced the plot (not desired). In the header `code_folding` is set to true. 

Here a linkt to a gist / code which hopefully makes clearer what I mean.
https://gist.github.com/werkstattcodes/d2d47e17720c8ecf2da16a23dde583e2

Many thanks!

**Comment by jjallaire** [comment]
Thanks for reporting, we'll fix this in the next release.

**Comment by werkstattcodes** [comment]
many thanks!  just realized that when I set `code_folding=NULL` (and `echo=F`) as a chunk option, the outcome is as intended.

**Comment by Felixmil** [comment]
I noticed the same behavior when `code_folding: true` was specified in the yaml header of the article (thus default option for all chunks): The `> Show Code` button was present for the chunks configured with `echo = FALSE`

**Comment by cderv** [comment]
@werkstattcodes thanks for the report. This is fixed now in dev version. `code_folding = FALSE` on chunk option was not correctly taken into account to not enforce `echo = TRUE`. 

@Felixmil setting `code_folding: true` in YAML will enforce `echo = TRUE` on all chunk. You need `code_folding = FALSE` to be able to set `echo = FALSE` on a chunk. This is by design for now with the `code_folding` option. If you think this default should be reconsider, please open a new issue specific to this - we can set discuss and get upvotes with the community.
