### ISSUE TITLE
option to disable all the styling features in distill

### ISSUE THREAD

**Issue by ardeeshany** [rstudio/distill#311]
Hi,

I was wondering if there is any feature that I can disable adding the css and/or JS elements distill added by default to the produced `html` file? I see we can add our own style, but still many predefined style will be added initially.

Thanks,
Ardalan

**Comment by cderv** [comment]
For theming, you can currently do two things: 

* Apply a CSS to override some rules of the default theme
* Provide a full custom Distill theme

This is explained in https://rstudio.github.io/distill/website.html#theming
and in the last blogpost: https://blog.rstudio.com/2020/12/07/distill/#theming

What is missing for you to customize your distill website ? 

> disable adding the css and/or JS elements distill added by default

Do you mean like removing all the CSS and JS inserted by default ? Distill has some dependencies you can't remove because they make it works. 

Do you have example of what you want to deactivate ?

**Comment by ardeeshany** [comment]
Thanks @cderv 

I have a pure template in HTML/CSS/JS (somthing like XaringanExtra::Panelset) and would like to include in the distill by the default styling of distill makes a conflict. Since my rempltea style is based on `bootstrap`, I was wondering if I can make the disable the style distil::article adds initially.

**Comment by cderv** [comment]
Do you want to keep some feature from **distill** though ? 
Using `distill::distill_article` format means you want to use distill style. You could use `rmarkdown::html_document` or `html_document_base` as base for your own format if you don't want **distill** feature. 

What part of the style do you want to change and [distill theming](https://rstudio.github.io/distill/website.html#theming) does not allow to do ?

**Comment by ardeeshany** [comment]
Hi @cderv 

Thanks for your response and suggestions. After taking look at distill package dependencies and the parts I need to change, I wrote my own template via `html_document` and it works now. Thanks again.

**Comment by cderv** [comment]
That is great ! 

I'll close this issue then. I think what you've done is ok ! Please reopen if you think we should do something different. Thanks!
