### ISSUE TITLE
Bug with categories containing accentuated character

### ISSUE THREAD

**Issue by larmarange** [rstudio/distill#331]
When there is an accentuated character (i.e. éèà...) in a categoy name, there is a bug when filtering posts by category.

Concrete example : https://larmarange.github.io/webin-R/seances.html#category:D%C3%A9butant

**Comment by larmarange** [comment]
Seems related to URL decoding.

**Comment by cderv** [comment]
Yes, it is related to URI decoding, I think we are missing a `decodeURIcomponent()` in here: 
https://github.com/rstudio/distill/blob/af58e083391765604895a88ad0adc07f2f44aed2/inst/rmarkdown/templates/distill_article/resources/listing.html#L56

`location.hash` is encoded and we need to decode it because it will be compare to `.post-metadata` JSON content which in not URI encoded.

Thanks for the report!

**Comment by cderv** [comment]
This should be fixed in dev version of **distill**
