### ISSUE TITLE
Using sass package to customize fonts

### ISSUE THREAD

**Issue by apreshill** [rstudio/distill#356]
The dev version now has: https://rstudio.github.io/sass/reference/font_face.html

Might be useful to test/document for distill.

This API now works: https://github.com/rstudio/bslib/issues/256

**Comment by apreshill** [comment]
Testing this out now today. I'm able to use Google fonts via the sass package, inside R chunks currently. It works locally:
<img width="1806" alt="Screen Shot 2021-04-16 at 11 44 47 AM" src="https://user-images.githubusercontent.com/12160301/115069947-2ad20280-9ea9-11eb-9702-0acb4b990166.png">

But not when deployed to GitHub Pages:
https://apreshill.github.io/sass-distill/

The font files end up in the `site_libs` directory: https://github.com/apreshill/sass-distill/tree/main/docs/site_libs

Obviously there is no sass processing from YAML currently, so I'm using sass in R code chunks. A few notes:

+ I'm adding the sass code chunks into `index.Rmd`. They render locally on the homepage, but don't affect other pages on the site (i.e., **about** is not affected)
+ No fonts render when deployed
+ I cannot figure out how to use sass to provide a CSS variable (not a Sass variable) to override a CSS variable we have in the theme file. For example this won't work to set the `--mono-font` variable:

```{r echo=TRUE}
mono <- font_google("Major Mono Display")
as_sass(list(
  # make the variable
  list("font-variable" = font_collection(mono, "system-ui")),
  # make the rule
  list("html{--mono-font: $font-variable}")
))
```

The html shows that the value of `$font-variable` is not processed (obviously b/c no Sass):

```
html {
	--mono-font: $font-variable;
}
```


If I try to use a normal CSS variable declaration without the sassy `$`, I see:

```
html {
	--mono-font: --font-variable;
}
```

**Comment by cderv** [comment]
This is a bit trickier than the other issue. Also, I am not sure to see completely how you would like this to work: using R chunk or using YAML like with **bslib**. 

First thing that could be possible is allowing one to use a `.scss` or `.sass` in the `theme` argument. This would just need to compile using `sass::sass()`. however, I am not sure if this is really of interest as `css` passed to `theme` are already mainly to define CSS variables. but this could allow allow to sassify this. 

Then, the chunk usage. Currently what you are doing above works because **sass** defines a `knit_print` method that will compile the resulting object using `sass::sass()` and add it as a HTML dependency to the current file using `tag$style()` but in the current HTML where it is in the body, not in the head. You can look at the html source. 
This is why it don't affect other pages because it will only be included in the body of this specific html file and not shared in a header across all site. 
To use a sass variable to set a CSS variable, you just need to take care of using a specific syntax - see https://sass-lang.com/documentation/breaking-changes/css-vars
This works 
````markdown
```{r echo=TRUE}
mono <- font_google("Major Mono Display")
as_sass(list(
  # make the variable
  list("font-variable" = font_collection(mono, "system-ui")),
  # make the rule
  list("html{--mono-font: #{$font-variable};}")
))
```
````

About the not-working-when-deployed, I believe the `.nojekyll` file must be in the `docs/` folder that you are using for Github pages (see for distill own website: https://github.com/rstudio/distill/blob/master/docs/.nojekyll) - this will make the folder starting with `_` unignore. See https://cderv.github.io/sass-distill/ where I just added the `.nojekyll` file. 


So on the sass variables topic, where do we go from there ? What is the user experience we want to offer using **sass** for customization ? 

I think we need to decide this and see then what needs to be done in the codebase. 

About the YAML handling in theme argument that can now be used with **rmarkdown** (https://github.com/rstudio/bslib/issues/256), this is handled by **bslib** on this front and not directly by **sass** - we have done nothing in **rmarkdown** except passing the content of `theme` to **bslib** when it is a list.

**Comment by apreshill** [comment]
Fair 🤣 

I was trying to see if I could just get fonts working with the stupidest solution possible first, following the sass package docs. I'll aim higher and focus on theme files. Thanks all!
