### ISSUE TITLE
Distill and gt tables

### ISSUE THREAD

**Issue by ymer** [rstudio/distill#399]
Distill changes the look and font size of tables, such as [gt.](https://gt.rstudio.com/).

If I adjust the font size in gt, it only adjusts the font size in the header.

**Comment by cderv** [comment]
Hi @ymer ! 

Thanks for reporting. Can you help us help your by providing a reproducible example that we can copy and run ? 
This would really help by knowing exactly what you tried and did not work as expected to see exactly how distill and gt interact with each other. This will allow us to know where the issue rely. 

It is highly possible that there is a conflict in styling between both CSS. There was in the past which has already been fixed: #159 and https://github.com/rstudio/gt/issues/643, but there could be others. 

With more details, it will be easier for us to add the correct rules.

Thanks!

**Comment by lmlicuanan** [comment]
Hi @cderv I believe this is the issue reproduced. Thanks!

```
---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r}
library(dplyr)
library(gt)

mtcars %>% 
  gt() %>% 
  tab_options(table.font.size = 5)
```
```

<img width="557" alt="image" src="https://user-images.githubusercontent.com/52149230/188420383-5e154f5c-2970-44a5-bab2-4438217f3e8e.png">

**Comment by cderv** [comment]
Thanks a lot @lmlicuanan ! 

Two main issues here: 

````markdown
```{r}
mtcars %>% 
  gt()
```
````

**gt** in **distill** does indeed gets its own CSS overwritten as there is a specific type for tables in **distill**. This is CSS introduced by Distill.js itself: 
```css
d-article table th, d-article table td {
    font-size: 15px;
    padding: 2px 8px;
}
```

It will applies on default gt() table, and when `tab_options(table.font.size = 5)` is set. It is just default gt is 16px, and default distill in 15px, so difference between heading and body does not stand out. 

When applying `tab_options(table.font.size = 5)`, it does not apply on the rows because of the CSS above. **gt** will add the css on `<table>` node, and rows will not use it as this is currently not overwritten by **gt**. The heading [has `font-size: 100%` applied on `.gt_col_heading`](https://github.com/rstudio/gt/blob/0af0588b6719e5596434c8cf4e84050c869dc0a7/inst/css/gt_styles_default.scss#L88), and there is [no such thing on the body](https://github.com/rstudio/gt/blob/0af0588b6719e5596434c8cf4e84050c869dc0a7/inst/css/gt_styles_default.scss#L183). 

@rich-iannone I can show you live the issue here, but I wonder if that would be worth adding a `font-size` rule in https://github.com/rstudio/gt/blob/0af0588b6719e5596434c8cf4e84050c869dc0a7/inst/css/gt_styles_default.scss#L183-L200

This way, you are sure that the rows will respect the attributes sets on `<table>` node.

**Comment by cderv** [comment]
@rich-iannone I fixed the issue on **distill** side by adding `font-size: 100%` rule on gt tables. 

If you think this can cause issue in other framework, maybe it is worth adding this rule you have for heading to row too.

**Comment by lmlicuanan** [comment]
works perfectly, thanks @cderv
