### ISSUE TITLE
homepage limited to 5 articles

### ISSUE THREAD

**Issue by lgnbhl** [rstudio/distill#403]
Hello,
After updating the distill R package to the most recent version, the homepage (index.html) of my blog is blank. However, reducing the number of articles in the `_posts` makes the page rendering correctly.

When I remove `visibility: hidden;` inside `index.html`, I have the same issue reported here: https://community.rstudio.com/t/distill-website-deployment-on-rstudio-connect-does-not-render-linked-articles/88900/6. 

Any idea how to fix that?

Thanks a lot!

**Comment by lgnbhl** [comment]
A quick fix would be to manually change `var max_posts = 25;` to `var max_posts = 6;` inside `index.html`. It would be great to be able to add this variable in the `_site.yml`. If this modification fixes the CSS issue shared above, the thumbnails are still not rendering in the index.html homepage :(

```  
function set_posts_visible(posts, visible) {
    if (visible) {

      // show bottom border by default
      $(posts).removeClass('post-preview-last');

      // apply limits if need be
      var max_posts = 25;
      var apply_limits = $('.posts-container').hasClass('posts-apply-limit');
      if (apply_limits && posts.length > max_posts) {
        posts = $(posts).slice(0, max_posts);
      } else {
        $('.posts-more a').addClass('hidden');
      }
```

**Comment by jhelvy** [comment]
After much trial and error, I discovered the same problem on the [Distillery site](https://distillery.rbind.io/). I could not for the life of me figure out what was going on until I removed the posts one at a time to find the magic number 5 worked. This must be a bug in a more recent version of {distill} because this didn't previously happen.

**Comment by lgnbhl** [comment]
Thank you for sharing @jhelvy.
Note that with my quick fix shared above (change 'var max_posts = 25;' to 'var max_posts = 6; in the 'index.html'), all the articles are accessible after clicking on "More articles »" in the bottom left of the homepage (at the exception of the thumbnails that are not rendering)

**Comment by jhelvy** [comment]
I'll do this. But this should be controllable in the site yml . There's an option to set the max number of feed times to display, e.g.

```
collections:
  posts:
    categories: true
    categories_metadata: true
    feed_items_max: 20
```

Perhaps this is being ignored?

**Comment by caayala** [comment]
Thanks for your work around @lgnbhl. 
I had the same issue in our blog: <https://blog.desuc.cl>

**Comment by p0bs** [comment]
Same issue here, too. I have a suspicion that this will be true for anyone who uses distill and updates their site

**Comment by cderv** [comment]
Hi everyone, 

sorry for the trouble with this issue. It took me a bit of time to find the source of the issue. 

This issue is caused by last **rmarkdown** release 2.11 which upgraded default JQuery to version 3. It seems there is a conflict with distill JS library that needs to be fixed. I am onto it. 

I believe you all are using **rmarkdown** 2.11, right ?

With this version, as a workaround waiting for a fix, you can set back the use of JQuery 2 using 
````r
options(rmarkdown.jquery.version = 2)
```` 
 * either before rendering, e.g
   ````r
   withr::with_options(
     list(rmarkdown.jquery.version = 2), 
     rmarkdown::render_site(".")
  )
  ````

 * either inside .Rprofile for the project (for example using `usethis::edit_r_profile("project")`)


These are temporary workaround, and we'll push a fix in the package very soon. 

Thanks for your patience.

**Comment by cderv** [comment]
The issue should now be fixed: I don't get a blank homepage anymore.

No need to do anything on your project except upgrading to last dev version of the package. 

````r
remotes::install_github("rstudio/distill")
````

If this does not fix the issue, or it was not the only thing happening for you @lgnbhl I'll reopen an have another look. 

Thanks

**Comment by lgnbhl** [comment]
Hi @cderv ,
Thanks a lot for this quick fix! It is working for me now 👍 .
I am wondering if it is possible to add a `max_posts` variable in the `_site.yml`? Does this functionnality already exist? Do you want me to create a new issue to ask for this feature?
Best,
Felix

**Comment by cderv** [comment]
> I am wondering if it is possible to add a max_posts variable in the _site.yml? Does this functionnality already exist? Do you want me to create a new issue to ask for this feature?

I need to look into this. Can you open a new issue so that we discuss and track this idea ? Thanks!

**Comment by caayala** [comment]
it's working again. Thanks!

**Comment by jhelvy** [comment]
Yup, the [distillery tips & tricks page](https://distillery.rbind.io/tips_and_tricks.html) is also back up - thanks for the quick fix @cderv!

**Comment by cderv** [comment]
Thanks all. I think we can consider the issue fixed then. 

Thanks for the report.
