### ISSUE TITLE
process of author name in the reference

### ISSUE THREAD

**Issue by huizezhang-sherry** [rstudio/distill#414]
I'm wondering if it is possible for the distill reference engine to do some automatic author name shortening (i.e. no matter whether the author field in the .bib is "Wickham, Hadley" or "Wickham, H", the output will always show as "Wickham, H"). The package `rticles` seems to do it by default and I'm wondering if distill can do that as well for html articles.

[Here](https://github.com/huizezhang-sherry/distill-example) is a minimal example.

**Comment by cderv** [comment]
Preview of the link HTML document example [here](https://refined-github-html-preview.kidonng.workers.dev/huizezhang-sherry/distill-example/raw/master/main.html)

Regarding the way the bibliography are shown, this is a matter of CSL. See about changing citation style using CSL when Pandoc citeproc is used: https://bookdown.org/yihui/rmarkdown-cookbook/bibliography.html#changing-citation-style

For example, this style from a specific journal seems to use shorter name only:
```yaml
csl: https://www.zotero.org/styles/acs-chemical-biology
```

Add this to your example, and you should see the result. 

So I think you need to choose the right CSL that suits the way you want references to be shown. 

Hope it helps

**Comment by cderv** [comment]
So I looked closer into this, and in fact **distill** won't work well this CSL 

> The package rticles seems to do it by default and I'm wondering if distill can do that as well for html articles.

Can you share which **rticles** format is giving you what you need ? 

I wonder if this is because the **rticles** format used, is leveraging LaTeX with `natbib` that maybe handles that. 

I need more details. 

But in short, **distill** does not do much about reference - Pandoc is the one doing citation processing. ( as mentioned in https://rstudio.github.io/distill/citations.html). So hopefully, using Pandoc citeproc can allow what you need.

**Comment by huizezhang-sherry** [comment]
It was a while ago with the R Journal. 

We managed to use a CSL file to standardize the reference and were wondering whether there is a simpler way to do this. 

But I don't think it is still an issue now.

**Comment by cderv** [comment]
OK good to know. Citation processing is done using Pandoc citeproc and we rely on it. There is not really and additional process we had and it is Citeproc which is resolving the reference, and using the CSL to know which style to use. 

Thank for asking the question here. Always welcome to here feedback. And sorry for the delay.
