### ISSUE TITLE
Code chunks not rendering correctly

### ISSUE THREAD

**Issue by mccarthy-m-g** [rstudio/distill#418]
I was working on a distill article and ran into an odd bug. The article discusses the lavaan package, which uses character strings to set up model formulas like so:

```r
model_syntax <- '
  f1 =~ y1 + y2 + y3 
  f2 =~ y4 + y5 + y6 
  f3 =~ y7 + y8 + y9 + y10
'
```

When I knitted my article, the assignment operator was unexpectedly moved to the bottom of the character string in the rendered output.

![distill_article](https://user-images.githubusercontent.com/51542091/139787767-895c5d9b-76b7-45b6-93b1-5d2d3a2f33f3.png)

Here's a minimal reproducible example of the R Markdown document.

``````
---
title: "Untitled"
output: distill::distill_article
---

```{r}
configural_model <- '
  # Measurement model
  w1comp =~ w1vst1 + w1vst2 + w1vst3
	w2comp =~ w2vst1 + w2vst2 + w2vst3
'
```
``````

The documents renders as expected when the output is `html_document`.

![html_document](https://user-images.githubusercontent.com/51542091/139788076-f075bcda-d527-4e13-ae62-987c76d79e69.png)

``````
---
title: "Untitled"
output: html_document
---

```{r}
configural_model <- '
  # Measurement model
  w1comp =~ w1vst1 + w1vst2 + w1vst3
	w2comp =~ w2vst1 + w2vst2 + w2vst3
'
```
``````

**Comment by cderv** [comment]
Thanks for the report. 

I believe this is an issue with **downlit** which is used by default in `distill_article()`. You get the correct behavior if you set 
````yaml
output: 
  distill::distill_article:
    highlight_downlit: false
````

This is because **downlit** will not generate a `span` for each line like Pandoc highlighter does. Which cause the behavior seen because of `display: inline-block;` applied on `<span>` following code. This is a CSS inserted by Pandoc which expect spans within spans 

Current workaround is to override this CSS using 
```css
pre > code.sourceCode > span {
  display: inherit;
}
```

either in a file or using a CSS chunk in the Rmd document. 

I'll report the issue to **downlit**

<details>
<summary>Produced by downlit</summary>

````html
<code class="sourceCode r"><span class="va">configural_model</span> <span class="op">&lt;-</span> <span class="st">'
  # Measurement model
  w1comp =~ w1vst1 + w1vst2 + w1vst3
  w2comp =~ w2vst1 + w2vst2 + w2vst3
'</span>
</code>
````

</details>

<details>
<summary>Produced by Pandoc</summary>

```html
<code class="sourceCode r"><span id="cb1-1">configural_model <span class="ot">&lt;-</span> <span class="st">'</span></span>
<span id="cb1-2"><span class="st">  # Measurement model</span></span>
<span id="cb1-3"><span class="st">  w1comp =~ w1vst1 + w1vst2 + w1vst3</span></span>
<span id="cb1-4"><span class="st">    w2comp =~ w2vst1 + w2vst2 + w2vst3</span></span>
<span id="cb1-5"><span class="st">'</span></span></code>
```
</details>

**Comment by mccarthy-m-g** [comment]
Thanks for the workaround and for passing this on @cderv!

**Comment by cderv** [comment]
This has been fixed in **downlit**
