### ISSUE TITLE
Level three header gets bold faced in the toc tab when used after xaringanExtra panel set

### ISSUE THREAD

**Issue by jeweljohnsonj** [rstudio/distill#428]
Problem: When a level three header is used after having a panel set from xaringanExtra package, the header is shown in bold face in the table of contents tab compared to the normal font face when the panel set is not in use. From the code below you can see that sub heading 1.2 is shown in bold in the toc tab because it is after a panel set whereas sub heading 2.2 is shown in a normal font face.  Any ideas to show sub heading 1.2 in normal font face?

Reproducible code below

````
---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: TRUE
    toc_depth: 3
---

```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = FALSE)
```

```{r panelset, echo=FALSE}
xaringanExtra::use_panelset()
```

## Heading 1

text text

### sub heading 1.1

text text

---
#panelset from xaringanExtra package
---
::: {.l-page}
::: {.panelset}
::: {.panel}
## tab 1 {.panel-name}

Some graph

```{r, fig.align = 'center'}
ggplot(iris, aes(Sepal.Length, Sepal.Width, fill = Species)) + geom_boxplot()
```

:::
:::
:::

### sub heading 1.2

## Heading 2

text text

### sub heading 2.1

Some graph

```{r}
ggplot(iris, aes(Sepal.Length, Sepal.Width, fill = Species)) + geom_boxplot()
```

### sub heading 2.2


````

**Comment by jeweljohnsonj** [comment]
![Screenshot_20211210_101220](https://user-images.githubusercontent.com/74355965/145521158-8bcefb7f-1983-42a6-8310-265eb06e0c0c.png)

**Comment by jeweljohnsonj** [comment]
![Screenshot_20211210_101220](https://user-images.githubusercontent.com/74355965/145521304-fc756b1e-19dc-48ff-bd25-7cf88651875a.png)

**Comment by gadenbuie** [comment]
My guess is that it has to do with the panel name being a level-2 heading (`##`) but the following heading is level-3 (`###`). Because panelset rewrites the content within it, the level-2 heading is taken out of the document and rewritten, kind of like this:

```
# panelset

<!-- ## Heading 1 -->

### Heading 1.2
```

This isn't semantically correct since its like skipping a level in a list. So my guess is that distill tries to recover the structure a bit by promoting Heading 1.2 to a level 2 heading.

I'd recommend moving `## Heading 1` above the panelset and then using span syntax for the panel names: `[Panel 1]{.panel-name}`. If that doesn't work, let me know and I'll take another look.

**Comment by gadenbuie** [comment]
After looking at the screenshot I realized I got the heading names wrong in my answer above. So on second thought I think you should instead try using `### tab 1` so the headings are all in alignment

**Comment by jeweljohnsonj** [comment]
@gadenbuie  Yes, it works! Thanks a lot. `### tab 1` did the job. So for any headers that come down the panel set, I have to set tab alignment correctly to match those headers. Thanks again.

**Comment by cderv** [comment]
I don't know if there is anything we should do in **distill**. It probably see the header at some point and don't know it should be ignored. We could detect `.panel-name` class but I am not sure we should add special case in **distill** for panelset. 

Using header for tab name is one of the syntax. You could also use 
````markdown
::: l-page
::: panelset
::: panel
[tab 1]{.panel-name}

Some graph

```{r, fig.align = 'center'}
ggplot(iris, aes(Sepal.Length, Sepal.Width, fill = Species)) + geom_boxplot()
```
:::
:::
:::
````
for that to work. 

So I would close the issue here. @gadenbuie what is your take on this ?

**Comment by jeweljohnsonj** [comment]
@cderv Thanks for your comment. Both  `## tab 1 {.panel-name}` and  `[tab1]{.panel-name}` gives the same result. I will stick with the second method of putting my tab name within `[  ]` like you suggested to avoid any ambiguity.  If there is nothing more to add then I will close this issue after a few days.

**Comment by gadenbuie** [comment]
I prefer

```
### Title {.panel-name}
```

because it's a bit more resilient. If for some reason the panelset JavaScript fails or doesn't load, your document will still have the correct structure and the panel names become headings that ensure your content is readable.

Beyond that, I don't think there's anything that distill should do to adapt to panelset.

**Comment by jeweljohnsonj** [comment]
Oh okay. That was helpful to know. Thank you for your answer @gadenbuie
