### ISSUE TITLE
Getting an error in import_post()

### ISSUE THREAD

**Issue by naman159** [rstudio/distill#452]
I wanted to import the post at "https://www.kristinabecvar.com/posts/2022-04-03-dacss-603-assignment-3/" in our distill blog so I used `distill::import_post("https://www.kristinabecvar.com/posts/2022-04-03-dacss-603-assignment-3/")`.
Received the following error:
```
Error in utils::download.file(url, destfile = destfile, mode = "wb", quiet = quiet,  : 
  cannot open URL 'https://www.kristinabecvar.com/posts/2022-04-03-dacss-603-assignment-3/'
In addition: Warning message:
In utils::download.file(url, destfile = destfile, mode = "wb", quiet = quiet,  :
  URL 'https://www.kristinabecvar.com/posts/2022-04-03-dacss-603-assignment-3/': status was 'SSL peer certificate or SSH remote key was not OK'
```

Could someone point me where the issues lies? I have had a couple more of these issues where HTTP status were '505 Unknown Error' and  '403 Forbidden'.

Sorry if this is the wrong place to ask this question and thanks!

**Comment by cderv** [comment]
The latter error you have means that it is not an issue with **distill** directly. Your R environment does not seems to be able to reach correctly some urls due to SSL certificate issue with `libcurl`. 

Could you try 
````r
base::curlGetHeaders("https://www.kristinabecvar.com/posts/2022-04-03-dacss-603-assignment-3/", verify = FALSE)
````

**distill** is using `utils::download.file` to retrieve the information. See `?utils::download.file`. There is a part about Secures URLs. 
It seems your OS doesn't have the correct certificate somehow, or the website have issue. 

You would need to tweak the options in order to solve this. Either by changing the download method or tweaking the configuration. By default `libcurl` is probably be used, and docs is https://curl.se/docs/sslcerts.html - not straightforward. 

You could try not using verification, this is not advice usually but if it is for a one time solution you could try. 
This can maybe be done by setting 
```r
options(download.file.method = "curl", download.file.extra="-k")
```

anyway, this is just some hints. You would need to find a way on your environment as downloads won't work correctly as long as SSL verification is done it seems

**Comment by naman159** [comment]
Thanks! That worked!

Seems to be an issue in my environment. I was able to import after running the `option` function.

PS: Apologies for the delayed response.

**Comment by cderv** [comment]
Glad it works now !
