### ISSUE TITLE
Description in _site.yaml causing Error "STRING_ELT() can only be applied to a 'character vector', not a 'list'"

### ISSUE THREAD

**Issue by cpsyctc** [rstudio/distill#490]
For some reason that completely baffles me, my distill site started giving that error every time I tried to knit some posts and reliably if knitting the whole site.  With help from Ivan Krylov and Duncan Murdoch I have fixed it for my site but with a bodge that makes no sense to me: everything is fine if leave out the description lines.  For ages, probably since I started the site, these were:
```
 description: |
  CE's pages "blog posts" about using R
```
I wondered if something had changed in distill and those quotation marks and apostrophe were now causing the problem but the error comes even if I reduce the description to a single word.  

This makes no sense to me and I have a fix so I move on.  However, Duncan agreed with my feeling that I should report it. There is a thread about this on the r-help list and I have branched the github repository which I think has the site when it was causing the problem: [https://github.com/cpsyctc/Rblog/tree/branch_with_error](https://github.com/cpsyctc/Rblog/tree/branch_with_error)

I am working on machine running Ubuntu 22.04.3 and my sessionInfo is:

```
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Paris
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] digest_0.6.33     fastmap_1.1.1     xfun_0.40         cachem_1.0.8      knitr_1.43        distill_1.5.4     memoise_2.0.1     htmltools_0.5.6   rmarkdown_2.24   
[10] cli_3.6.1         downlit_0.4.3     withr_2.5.0       compiler_4.3.1    rstudioapi_0.15.0 tools_4.3.1       evaluate_0.21     yaml_2.3.7        rlang_1.1.1   
``` 

I hope I'm not wasting people's time reporting this.  Huge gratitude for distill!  Chris

**Comment by cderv** [comment]
Thanks a lot for opening the issue. I think we were mysteriously missing a edge case.  Thanks a lot for the github repo as example, it was quite useful to fix ! 

First, let me explain what happened with your repo.

The error you encounter is a XML creation issue. We had a similar one in https://github.com/rstudio/distill/issues/448 and this oriented my search to usage of `description` field inside files. 

For the context, a RSS feed is created with XML for listings (https://rstudio.github.io/distill/blog.html#rss-feed) and the condition to trigger this is `description` and `site_url` inside`_site.yml`. This why you "solved" your issue by removing `description` field in your config file - it opt-out RSS feed for listings by doing that. But the real issue is not there. 

Knowing it would be something related to listing and description, I targeted this in my debug.  By trying to render your website in debug mode with distill, I found that the file creating the issue is [OMbook_glossary.Rmd](https://github.com/cpsyctc/Rblog/blame/branch_with_error/_posts/2021-11-09-ombookglossary/OMbook_glossary.Rmd). As you can see this file as no `description` field. And this is the real issue. If you add a `description` to this post, then it will work. 

Though, **distill** should have handle that as when no `description` is provided, the `title` should be used. But for an unknown reason, it seems this has never worked because there was a R to -> JSON -> R conversion happening, and `NULL` was transformed to `list()` and we tried to write this empty list to XML. Anyhow, I have a fix that I will push. 

Regarding why this happen recently, maybe this is because, from commit history, you tinkered with `collection` and `categories`. This triggered the listing feature that was not present before. 

Anyhow, no `description` field should not have been an issue for **distill**, and thanks to you it means there was more to #448 report. 

thank you !
