### ISSUE TITLE
Add nocite capability

### ISSUE THREAD

**Issue by garthtarr** [rstudio/distill#83]
If it exists, I haven't worked out how to do it, but it would be great to be able to include additional references that aren't explicitly cited in the text.  In LaTeX this would be `\nocite{}` and in R it can be done with `RefManageR::NoCite()`.

**Comment by schaubst** [comment]
I just spent an hour trying to get nocite to work for my distill website (work in progress). I would like to add myself to the line of people who would like to see this feature added.

**Comment by jjallaire** [comment]
I think the problem is that the distill javascript library is generating the bibliography rather than pandoc. The solution is to leave it to pandoc (then we get all the capabilities we are familiar with including nocite, csl, etc. I'm not able to work on this right now but should be able to within a few weeks. Will update the thread once a change has been pushed.

**Comment by jjallaire** [comment]
I just pushed a change that should address this (we now use pandoc to generate the bibliography rather than the distill framework): https://github.com/rstudio/distill/commit/e8585bcb29a8e4eba3e5c9e0403ac9a1cb316a17

You can install this with `remotes::install_github("rstudio/distill")`
